openapi: 3.0.3
info:
  title: Jstl.ink API
  description: |-
    Jstl.ink gives users the ability to easily create simple pages containing for 
    them relevant links and their social media profiles
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0

servers:
  - url: localhost:8080
  - url: https://api.jstl.ink.paulus.rocks

tags:
  - name: page
    description: Everything about jstlink pages
  - name: creator
    description: Everything about the creator page to create & edit pages

paths:
  /{pageId}:
    get:
      tags:
        - page
      summary: Get page by pageId
      description: Returns a single page
      operationId: getPageById
      parameters:
        - $ref: '#/components/parameters/PageId'
      responses:
        '200':
          $ref: '#/components/responses/PageResponse'
        '404':
          description: Page not found

  /creator:
    post:
      tags:
        - creator
      summary: Create new user page
      operationId: createPage
      requestBody:
        required: true
        x-codegen-request-body-name: body
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  $ref: '#/components/schemas/Id'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          description: PageId already exists
        '200':
          $ref: '#/components/responses/PageResponse'
      security:
        - bearerAuth: [ ]

  /creator/{pageId}:
    get:
      tags:
        - creator
      summary: Get the creator page
      operationId: getCreatorPageById
      parameters:
        - $ref: '#/components/parameters/PageId'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/PageResponse'
      security:
        - bearerAuth: [ ]
    post:
      tags:
        - creator
      summary: Create new link on the user page
      operationId: createLinkByPageId
      parameters:
        - $ref: '#/components/parameters/PageId'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/LinkResponse'
      security:
        - bearerAuth: [ ]
    delete:
      tags:
        - creator
      summary: Delete a user page
      operationId: deletePageByPageId
      parameters:
        - $ref: '#/components/parameters/PageId'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/SuccessfulResponse'
      security:
        - bearerAuth: [ ]
    put:
      tags:
        - creator
      summary: Update a social link on user page
      operationId: updateSocialLinkByPageId
      parameters:
        - $ref: '#/components/parameters/PageId'
      requestBody:
        required: true
        x-codegen-request-body-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialLink'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialLink'
      security:
        - bearerAuth: [ ]
    patch:
      tags:
        - creator
      summary: Update a link on user page
      operationId: updateLinkByPageId
      parameters:
        - $ref: '#/components/parameters/PageId'
      requestBody:
        required: true
        x-codegen-request-body-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Link'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '200':
          $ref: '#/components/responses/LinkResponse'
      security:
        - bearerAuth: [ ]

  /creator/logout:
    get:
      tags:
        - creator
      summary: Logout user from creator page
      operationId: logoutUser
      parameters:
        - $ref: '#/components/parameters/PageId'
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulResponse'

components:
  schemas:
    Id:
      description: ID of page
      type: string

    Page:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          description: username user page
          type: string
        bio:
          description: biography for user page
          type: string
        img:
          type: string
          description: url for image
        socialLinks:
          type: array
          description: links for social media profiles
          items:
            $ref: '#/components/schemas/SocialLink'
        links:
          type: array
          description: custom definable links
          items:
            $ref: '#/components/schemas/Link'

    Link:
      type: object
      required:
        - name
        - link
      properties:
        name:
          description: alias for link
          type: string
        link:
          description: url of a link
          type: string

    SocialLink:
      $ref: '#/components/schemas/Link'

  #################

  parameters:
    PageId:
      name: pageId
      in: path
      description: ID of order that needs to be fetched
      required: true
      schema:
        $ref: '#/components/schemas/Id'

  #################

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

    SuccessfulResponse:
      description: successful operation

    LinkResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Link'#
        application/xml:
          schema:
            $ref: '#/components/schemas/Link'

    PageResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Page'
        application/xml:
          schema:
            $ref: '#/components/schemas/Page'

  #################

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT