openapi: 3.0.3
info:
  description: "Jstl.ink gives users the ability to easily create simple pages containing\
    \ for \nthem relevant links and their social media profiles"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Jstl.ink API
  version: 0.1.0
servers:
- url: localhost:8080
- url: https://jstl.ink
tags:
- description: Everything about jstlink pages
  name: page
- description: Everything about the creator page to create & edit pages
  name: creator
paths:
  /{pageId}:
    get:
      description: Returns a single page
      operationId: getPageById
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
            application/xml:
              schema:
                $ref: '#/components/schemas/Page'
          description: successful operation
        "404":
          description: Page not found
      summary: Get page by pageId
      tags:
      - page
      x-eov-operation-handler: controllers/PageController
  /creator:
    post:
      operationId: createPage
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
            application/xml:
              schema:
                $ref: '#/components/schemas/Page'
          description: successful operation
      security:
      - bearerAuth: []
      summary: Create new user page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
  /creator/{pageId}:
    delete:
      operationId: deletePageByPageId
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          description: successful operation
      security:
      - bearerAuth: []
      summary: Delete a user page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
    get:
      operationId: getCreatorPageById
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
            application/xml:
              schema:
                $ref: '#/components/schemas/Page'
          description: successful operation
      security:
      - bearerAuth: []
      summary: Get the creator page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
    patch:
      operationId: updateLinkByPageId
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Link'
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
            application/xml:
              schema:
                $ref: '#/components/schemas/Link'
          description: successful operation
      security:
      - bearerAuth: []
      summary: Update a link on user page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
    post:
      operationId: createLinkByPageId
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
            application/xml:
              schema:
                $ref: '#/components/schemas/Link'
          description: successful operation
      security:
      - bearerAuth: []
      summary: Create new link on the user page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
    put:
      operationId: updateSocialLinkByPageId
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialLink'
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialLink'
          description: successful operation
      security:
      - bearerAuth: []
      summary: Update a social link on user page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
  /creator/logout:
    get:
      operationId: logoutUser
      parameters:
      - description: ID of order that needs to be fetched
        explode: false
        in: path
        name: pageId
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Logout user from creator page
      tags:
      - creator
      x-eov-operation-handler: controllers/CreatorController
components:
  parameters:
    PageId:
      description: ID of order that needs to be fetched
      explode: false
      in: path
      name: pageId
      required: true
      schema:
        $ref: '#/components/schemas/Id'
      style: simple
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    SuccessfulResponse:
      description: successful operation
    LinkResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Link'
        application/xml:
          schema:
            $ref: '#/components/schemas/Link'
      description: successful operation
    PageResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Page'
        application/xml:
          schema:
            $ref: '#/components/schemas/Page'
      description: successful operation
  schemas:
    Id:
      description: ID of page
      format: int64
      type: integer
    Page:
      example:
        img: img
        socialLinks:
        - null
        - null
        name: name
        bio: bio
        links:
        - name: name
          link: link
        - name: name
          link: link
        id: 0
      properties:
        id:
          description: ID of page
          format: int64
          type: integer
        name:
          description: username user page
          type: string
        bio:
          description: biography for user page
          type: string
        img:
          description: url for image
          type: string
        socialLinks:
          description: links for social media profiles
          items:
            $ref: '#/components/schemas/SocialLink'
          type: array
        links:
          description: custom definable links
          items:
            $ref: '#/components/schemas/Link'
          type: array
      required:
      - id
      - name
      type: object
    Link:
      example:
        name: name
        link: link
      properties:
        name:
          description: alias for link
          type: string
        link:
          description: url of a link
          type: string
      required:
      - link
      - name
      type: object
    SocialLink:
      $ref: '#/components/schemas/Link'
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
